### ISSUE TITLE
i would like to become a repo maintainer & a contributer

### ISSUE THREAD

**Issue by abolfazlchaman** [reactjs/fa.react.dev#330]
Hi hope you are doing well,

as suggested by [gaearon](https://github.com/gaearon) in the [reference here](https://github.com/reactjs/translations.react.dev/pull/283#issuecomment-1528572626),

I'm "Abolfazl Chaman" & am 20 years old, I have been coding since I was 13, started web development in 2018, and got to know React, js, node.js, express & several other related technologies pretty well, since then worked on mostly large-scale closed source projects. I translated the official very well-known [Airbnb-javascript-style-guide](https://github.com/abolfazlchaman/javascript-style-guide), as well as their official [React/JSX-style-guide](https://github.com/abolfazlchaman/javascript-style-guide/tree/master/react) as well as their [CSS/Sass-style-guide](https://github.com/abolfazlchaman/css-style-guide) .

For translation and maintaining capability proof: I'm a holder of an Academic IELTS(International English Language Testing System) Band 7.5 test results and Farsi(Persian) is my mother tongue.

I have the time & skills necessary to be an active & consistent member of the maintaining fa translation team and certainly would be very much honored to work with talented & awesome engineers like you. -Best wishes!🤝
@sJJdGG @rezvani2647 @sorousht @zahrajoulaei @Schabaani @masoud-bahrami

**Comment by rezvani2647** [comment]
That's wonderful we definitely need a person like you. I'm looking forward to have you as a maintainer

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Abolfazl Chaman ***@***.***>
Sent: Sunday, April 30, 2023 7:47:09 PM
To: reactjs/fa.react.dev ***@***.***>
Cc: Abolfazl Rezvani Naraqi ***@***.***>; Mention ***@***.***>
Subject: [reactjs/fa.react.dev] i would like to become a repo maintainer & a contributer (Issue #330)


Hi hope you are doing well,

as suggested by gaearon<https://github.com/gaearon> in the reference here<https://github.com/reactjs/translations.react.dev/pull/283#issuecomment-1528572626>,

I'm "Abolfazl Chaman" & am 20 years old, I have been coding since I was 13, started web development in 2018, and got to know React, js, node.js, express & several other related technologies pretty well, since then worked on mostly large-scale closed source projects. I translated the official very well-known Airbnb-javascript-style-guide<https://github.com/abolfazlchaman/javascript-style-guide>, as well as their official React/JSX-style-guide<https://github.com/abolfazlchaman/javascript-style-guide/tree/master/react> style guide as well as their CSS/Sass-style-guide<https://github.com/abolfazlchaman/css-style-guide> .

For translation and maintaining capability proof: I'm a holder of an Academic IELTS(International English Language Testing System) Band 7.5 test results and Farsi(Persian) is my mother tongue.

I have the time & skills necessary to be an active & consistent member of the maintaining fa translation team and certainly would be very much honored to work with talented & awesome engineers like you. -Best wishes!🤝
@sJJdGG<https://github.com/sJJdGG> @rezvani2647<https://github.com/rezvani2647> @sorousht<https://github.com/sorousht> @zahrajoulaei<https://github.com/zahrajoulaei> @Schabaani<https://github.com/Schabaani> @masoud-bahrami<https://github.com/masoud-bahrami>
